name: DevOps Bot CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps: 
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build Docker Image
    run: |
      docker build -t chandanashettybs/devops-troubleshooting-bot:latest .

  - name: Push Docker Image
    run: |
      docker push chandanashettybs/devops-troubleshooting-bot:latest

  - name: Setup kubectl
    uses: azure/setup-kubectl@v4

  - name: Setup Helm
    uses: azure/setup-helm@v4

  - name: Configure kubeconfig
    run: |
      mkdir -p $HOME/.kube
      echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

  - name: Deploy with Helm
    run: |
      helm upgrade --install devops-bot ./devops-bot-chart -n devops-bot